stages:
  - check

check:
  stage: check
  image: node:20.11.0-alpine
  before_script:
    # helyi függőségek feltelepítése
    - npm install
  script:
    # eslint futtatása
    - npx eslint .
    # typescript transzpilálás
    - npx tsc
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - "node_modules/"
      - "**/node_modules"
